default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: OffileProjectApi_development

test:
  <<: *default
  database: OffileProjectApi_test

production:
  <<: *default
  database: OffileProjectApi_production
